### ISSUE TITLE
Brug for PSD

### ISSUE THREAD

**Issue by dongfangyier** [SpectrumApp/spectrum-python#13]
Hello, I'm trying to find PSD by brug method, but I have some problems. Not all the frequencies of the PSD I care about, I only care about the lower frequencies. But it takes me too much time to find and intercept the PSD because of the huge amount of data. Is there a way that I can only find the PSD in the low frequency band, or the PSD in the specific frequency band? Thank you.

**Comment by frankwiles** [comment]
I'm sorry, I don't see how this has anything to do with this library.
